// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exaysroxomljpqxhbudr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4YXlzcm94b21sanBxeGhidWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjE0OTgsImV4cCI6MjA2Mjc5NzQ5OH0.es18hOTRacVMhooUcImLIdDw-3Gs7ME2g_oMYIae5Ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);